command=$SCRIPT_DIR/$BLOCK_NAME
color=#E0E0E0

align=center
color=#D7D0C7
separator_block_width=14

[memory]
command=/home/teo/.config/i3/scripts/memory
label=
interval=30

[cpu_usage]
command=/home/teo/.config/i3/scripts/cpu_usage
label=
interval=10

[load_average]
command=/home/teo/.config/i3/scripts/load_average
interval=1
label=

[disk]
command=/home/teo/.config/i3/scripts/disk
interval=1
label=

[volume]
command=/home/teo/.config/i3/scripts/volume
label= 
interval=once	

[time]
command=date '+%d %b %Y %H:%M'
interval=1
label=
color=#93BF55

[exit_menu]
label=
command=/home/teo/.config/i3/scripts/exit_menu
